trigger:
- v2.2.1-vsmac

pr:
- v2.2.1-vsmac

pool:
  vmImage: ubuntu-latest

variables:
- name: Codeql.Enabled
  value: true
- name: Codeql.TSAEnabled
  value: true

steps:

- task: CodeQL3000Init@0
  # condition: eq(variables['Build.SourceBranchName'], 'v2.2.1-vsmac')
  inputs:
    Enabled: true

- task: DotNetCoreCLI@2
  displayName: Build and Package
  inputs:
    command: build
    arguments: '-c Release'

- task: CodeQL3000Finalize
  # condition: eq(variables['Build.SourceBranchName'], 'v2.2.1-vsmac')
  inputs:
    Enabled: true

- task: DotNetCoreCLI@2
  displayName: Push
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'v2.2.1-vsmac'))
  inputs:
    command: push
    searchPatternPush: 'packages/Release/**.nupkg'
    feedPublish: 'Xamarin'