trigger:
- v2.2.1-vsmac

pr:
- v2.2.1-vsmac

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  displayName: Build and Package
  inputs:
    command: build
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  displayName: Push
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'v2.2.1-vsmac'))
  inputs:
    command: push
    searchPatternPush: 'packages/Release/**.nupkg'
    feedPublish: 'Xamarin'